declare module 'three' {
  export type Vector2 = any; export const Vector2: any;
  export type Vector3 = any; export const Vector3: any;
  export type Quaternion = any; export const Quaternion: any;
  export type Matrix4 = any; export const Matrix4: any;
  export type Color = any; export const Color: any;
  export type Group = any; export const Group: any;
  export type Scene = any; export const Scene: any;
  export type Mesh = any; export const Mesh: any;
  export type InstancedMesh = any; export const InstancedMesh: any;
  export type Object3D = any; export const Object3D: any;
  export type BufferGeometry = any; export const BufferGeometry: any;
  export type BufferAttribute = any; export const BufferAttribute: any;
  export type Line = any; export const Line: any;
  export type LineSegments = any; export const LineSegments: any;
  export type LineBasicMaterial = any; export const LineBasicMaterial: any;
  export type CanvasTexture = any; export const CanvasTexture: any;
  export type DataTexture = any; export const DataTexture: any;
  export type Material = any; export const Material: any;
  export type MeshStandardMaterial = any; export const MeshStandardMaterial: any;
  export type MeshToonMaterial = any; export const MeshToonMaterial: any;
  export type MeshBasicMaterial = any; export const MeshBasicMaterial: any;
  export type ShaderMaterial = any; export const ShaderMaterial: any;
  export type PerspectiveCamera = any; export const PerspectiveCamera: any;
  export type WebGLRenderer = any; export const WebGLRenderer: any;
  export type DirectionalLight = any; export const DirectionalLight: any;
  export type HemisphereLight = any; export const HemisphereLight: any;
  export type AmbientLight = any; export const AmbientLight: any;
  export type FogExp2 = any; export const FogExp2: any;
  export type Ray = any; export const Ray: any;
  export type Box3 = any; export const Box3: any;
  export type Clock = any; export const Clock: any;
  export const PlaneGeometry: any;
  export const BoxGeometry: any;
  export const CapsuleGeometry: any;
  export const SphereGeometry: any;
  export const CylinderGeometry: any;
  export const TorusGeometry: any;
  export const RingGeometry: any;
  export const IcosahedronGeometry: any;
  export const MathUtils: any;
  export const RepeatWrapping: any;
  export const SRGBColorSpace: any;
  export const DoubleSide: any;
  export const BackSide: any;
  export const AdditiveBlending: any;
  export const LinearMipmapLinearFilter: any;
  export const LinearFilter: any;
  export const NearestFilter: any;
  export const RGBFormat: any;
  export const ACESFilmicToneMapping: any;
  export const PCFSoftShadowMap: any;
}
